services:
  - type: web
    name: av-prop-mission
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    disk:
      name: avprop-data
      mountPath: /var/data
      sizeGB: 1